FROM php:8.2-apache

RUN apt-get update && apt-get install git unzip zip curl -y

RUN docker-php-ext-install mysqli
RUN a2enmod rewrite

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Instalar cliente Meilisearch
WORKDIR /var/www/html
COPY ./web /var/www/html

RUN composer install

RUN composer require meilisearch/meilisearch-php
RUN composer require guzzlehttp/guzzle php-http/guzzle7-adapter
